# Generated by Django 4.2.3 on 2023-08-17 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posteos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("desarrollo", models.TextField(default=None)),
                ("fechaSolicitud", models.DateField(default=django.utils.timezone.now)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name="propuestas",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="propuestas",
            name="Contacto",
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="propuestas",
            name="desarrollo",
            field=models.TextField(default=None),
        ),
    ]
