# Generated by Django 4.2.3 on 2023-08-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0003_avatar"),
    ]

    operations = [
        migrations.RenameField(
            model_name="propuestas",
            old_name="Contacto",
            new_name="contacto",
        ),
    ]
